### ISSUE TITLE
name of created zip file for p2 classifier is wrong

### ISSUE THREAD

**Issue by Dennis-Koch** [annafed/kar2tycho-maven-plugin#3]
the file name for the zipped p2 repository in the target directory is named ${artifactId}${version}-p2.zip. It is missing the "-" (dash) between artifact and version. The name gets to its correct pattern when the file is installed or deployed. This is of course only an issue then if you need (for whatever reason) a scripted access directly to the generated zip file.

As an example you might need this direct access if you have to execute maven with the "verify" goal instead of install or deploy.

**Comment by annafed** [comment]
Fixed in 1.3.0- snapshot
